# Date : 11-03-2025
# Numpy Library

In [6]:
import numpy as np

In [7]:
np.__version__

'1.26.4'

In [9]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [12]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [13]:
type(my_list)

list

In [14]:
arr = np.array(my_list)

In [15]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
Difference : in array array keyword is displayed : array[] , in list only [] displayed

In [16]:
type(arr)

numpy.ndarray

In [17]:
type(my_list)

list

In [18]:
np.arange(15) # print array range from 0-14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Date : 12-03-2025

In [ ]:
# How indexes is works with matrix

In [19]:
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [27]:
np.arange(15) # 15 refer to the index 0-14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3.0)

array([0., 1., 2.])

In [24]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(10,20) #starting fro index 10 to 20 i.e n-1 19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
np.arange(20,10)  # 1st argument should be < 2nd argument 

array([], dtype=int32)

In [30]:
np.arange(-20,10) # -20 to n-1

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [31]:
np.arange(-16,10) # -16 index to n-1

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [32]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [33]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [34]:
np.arange() # Iq  : it miss stop argument

TypeError: arange() requires stop to be specified.

In [35]:
np.arange(10,30,5) # n-1 30-1 = 29

array([10, 15, 20, 25])

In [36]:
np.arange(0,10,3)  # 0 to n-1 = 9

array([0, 3, 6, 9])

In [ ]:
np.arange(10,30,5,8)  # we cant pass four arguments in range

In [37]:
np.zeros(10)  # parameter tunning by default zeros datatype is float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.zeros(5, dtype = int)  # Hyper parameter tunning 

array([0, 0, 0, 0, 0])

In [41]:
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [45]:
zero = np.zeros((2,2)) # give two brackets and dimentions value
zero

array([[0., 0.],
       [0., 0.]])

In [43]:
print(type(zero))

<class 'numpy.ndarray'>


In [46]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [48]:
np.zeros((3,3)) # 3,3 means dimension

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [50]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [55]:
print(np.zeros(n,dtype = int))  # hyper parameter tunning dtype is inbuilt data type

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [56]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [138]:
n

(6, 7)

In [139]:
n1

(6, 8)

In [140]:
type(n1)

tuple

In [141]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# print 1D , 2D array

In [82]:
print(np.arange(2,5)) # 1d array

[2 3 4]


In [68]:
print(np.arange(-1,5))

[-1  0  1  2  3  4]


In [81]:
print(np.zeros(5)) #1d array 

[0. 0. 0. 0. 0.]


In [80]:
print(np.zeros((2,2))) #parameter tunning

[[0. 0.]
 [0. 0.]]


In [79]:
print(np.zeros((2,2),dtype = int )) #hypertunning

[[0 0]
 [0 0]]


In [84]:
print(np.zeros((5,10),dtype = int ))  # N Dimension array

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [85]:
np.ones(3)

array([1., 1., 1.])

In [86]:
np.ones(3 , dtype=int)  # 1 Dimension array

array([1, 1, 1])

In [88]:
np.ones((2,2) ,dtype = int)  # 2 Dimension array

array([[1, 1],
       [1, 1]])

In [89]:
np.ones((5,7) ,dtype = int)  # n Dimension array

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [ ]:
n=4

In [87]:
np.ones(n) 

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [90]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [91]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [92]:
range(5)

range(0, 5)

In [142]:
r1 = range(5)
type(r1)

range

In [93]:
r = range(5)
r

range(0, 5)

In [94]:
for i in r:
    print(i)

0
1
2
3
4


In [96]:
list(range(5))

[0, 1, 2, 3, 4]

In [97]:
range(1,10)

range(1, 10)

In [98]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [99]:
list(range(1,10,3))

[1, 4, 7]

In [100]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [101]:
rand(2,3)

NameError: name 'rand' is not defined

In [ ]:
# Random function create random values

In [102]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [103]:
np.random.rand(3,2)

array([[0.11880249, 0.93229256],
       [0.36246756, 0.67933405],
       [0.48757928, 0.91741295]])

In [104]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [143]:
np.random.rand(3) # 1d array

array([0.50437951, 0.35535369, 0.24099132])

In [105]:
np.random.rand(3,5) # 2d array

array([[0.12894344, 0.06937869, 0.41309825, 0.17083079, 0.38228404],
       [0.98104266, 0.43716973, 0.56454833, 0.72331783, 0.04905527],
       [0.52048389, 0.46415025, 0.84835449, 0.41929873, 0.76376744]])

In [120]:
np.random.randint(2,10) #Create random values between 2-9 (2 included ,10 excluded)

2

In [129]:
np.random.randint(4,6) # 2nd argument excluded

4

In [130]:
np.random.randint(10,20,5)  #Generate 5 random number between 10 - 19 ,20 is excluded

array([17, 15, 15, 15, 17])

In [131]:
np.random.randint(1,6,4) 

array([4, 4, 1, 5])

In [144]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [145]:
np.random.randint(-30,20,10) #from -30 to n-1 print 10 numbers

array([-30, -25,   9, -24,  -2, -17,   0,   9, -22,   8])

In [146]:
np.random.randint(20,30,10) 

array([20, 27, 26, 21, 20, 24, 26, 20, 20, 20])

In [151]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

8

In [152]:
np.random.randint(10,21,3)

array([12, 14, 15])

In [153]:
np.random.randint(1,12,10)

array([3, 2, 5, 6, 5, 1, 7, 5, 1, 6])

In [164]:
np.random.randint(0,1)

0

In [165]:
np.random.randint(10,40,(4,4)) #generre the element 10 -30 with 4*4 mtri

array([[28, 19, 14, 23],
       [24, 19, 26, 29],
       [13, 10, 27, 21],
       [33, 24, 20, 37]])

In [166]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[65, 21, 62, 16, 83, 74, 24,  8, 36, 57, 86, 84],
       [46, 20, 82, 30, 42, 78, 89, 47, 27, 64, 60, 76],
       [49, 33, 48, 11, 76, 10, 64, 15, 52, 27, 60, 83],
       [79, 84, 47, 98, 60, 93, 23, 76, 27, 42, 79, 48],
       [27, 29, 97, 52, 72, 40, 79, 59, 15,  3, 88, 40],
       [ 1, 15, 55, 60, 71, 63, 41, 10, 39,  6, 15, 37],
       [56, 12, 47, 11, 25, 52, 96,  6, 85, 71, 25, 21],
       [83, 25, 39, 12, 87, 41, 24, 36, 62, 57, 36, 66],
       [50, 58,  5, 60, 20, 81, 45, 50, 43, 93, 78, 69],
       [13,  6, 34, 42, 59, 17, 30, 68, 65, 38, 72, 28],
       [92, 63, 36,  9, 78, 96, 54,  2, 93, 38, 81, 62],
       [64, 97, 99,  3, 53, 41, 85, 51, 99, 46, 59,  5]])

In [132]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [133]:
np.arange(1,13).reshape(3,4) #3*4=12 total 12 values 1-13 has 12 values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
np.arange(1,13).reshape(5,4) #5*4=20 cannot reshape

ValueError: cannot reshape array of size 12 into shape (5,4)

In [136]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [137]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [167]:
b = np.random.randint(10,20,(5,4))
b

array([[18, 10, 17, 13],
       [15, 19, 16, 10],
       [10, 10, 15, 19],
       [13, 14, 18, 14],
       [14, 13, 18, 14]])

In [168]:
type(b)

numpy.ndarray

In [169]:
b

array([[18, 10, 17, 13],
       [15, 19, 16, 10],
       [10, 10, 15, 19],
       [13, 14, 18, 14],
       [14, 13, 18, 14]])